title: "AgentCraft"
description: "IUI 2026 · March 23–26, 2026 · Paphos, Cyprus"

# Use the Minimalistic theme via remote_theme (works on GitHub Pages)
remote_theme: https://github.com/vaibhavvikas/jekyll-theme-minimalistic

# Required for remote themes on GitHub Pages
plugins:
  - jekyll-remote-theme
  - jemoji

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - README.md
  - mise.toml

# Appearance
color-scheme: auto
logo: /assets/img/agentcraft.png
logo-description: "A yellow robot being painted in watercolor by a human hand. AIA Entirely AI, Human-initiated, Reviewed, DreamStudio v1.0 (https://aiattribution.github.io/statements/AIA-EAI-Hin-R-?model=DreamStudio-v1.0)"
favicon: false

# Navigation (left sidebar). Treat markdown pages as .html with section anchors.
navigation:
  - name: Home
    link: /
  - name: Call for Participation
    link: ./cfp
  - name: Organizers
    link: ./organizers#organizers
  - name: Program Committee
    link: ./organizers#program-committee
  - name: Contact
    link: ./organizers#contact

# Optional: Google Analytics (replace with your ID if you have one)
# google_analytics: G-XXXXXXXXXX
